name = "GNSSDecoder"
uuid = "bf6b1ec8-12ad-4501-972c-3dec0d675c2b"
version = "3.0.0"
authors = ["Soeren Schoenbrod <soeren.schoenbrod@nav.rwth-aachen.de>", "Michael Niestroj <michael.niestroj@nav.rwth-aachen.de>", "Erik Deinzer <erikdeinzer@gmail.com>"]

[deps]
Aff3ct = "529ff742-b572-47ff-bc84-d3f557f53d2b"
BitIntegers = "c3b6d118-76ef-56ca-8cc7-ebb389d030a1"
DataStructures = "864edb3b-99cc-5e75-8d2d-829cb0a9cfe8"
Dictionaries = "85a47980-9c8c-11e8-2b9f-f7ca1fa99fb4"
DocStringExtensions = "ffbed154-4ef7-542d-bbb7-c09d3a79fcae"
GNSSSignals = "52c80523-2a4e-5c38-8979-05588f836870"

[compat]
Acquisition = "2"
Aff3ct = "1"
Aqua = "0.8"
BitIntegers = "0.2.6, 0.3.5"
DataStructures = "0.18, 0.19"
Dictionaries = "0.4"
DocStringExtensions = "0.6, 0.7, 0.8, 0.9"
Downloads = "1"
GNSSSignals = "2.3"
Random = "1"
Test = "1"
Tracking = "2"
Unitful = "1"
ZipFile = "0.10"
julia = "1.10"

[extras]
Acquisition = "d4bbf60b-102b-5ffb-8f97-a7ea5817e69f"
Aqua = "4c88cf16-eb10-579e-8560-4a9242c79595"
Downloads = "f43a241f-c20a-4ad4-852c-f6b1247861c6"
Random = "9a3f8284-a2c9-5f02-9a11-845980a1fd5c"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"
Tracking = "10b2438b-ffd4-5096-aa58-44041d5c8f3b"
Unitful = "1986cc42-f94f-5a68-af5c-568840ba703d"
ZipFile = "a5390f91-8eb1-5f08-bee0-b1d1ffed6cea"

[targets]
test = ["Acquisition", "Aqua", "Downloads", "Random", "Test", "Tracking", "Unitful", "ZipFile"]
