name = "GNSSDecoder"
uuid = "bf6b1ec8-12ad-4501-972c-3dec0d675c2b"
authors = ["Soeren Schoenbrod <soeren.schoenbrod@nav.rwth-aachen.de>", "Michael Niestroj <michael.niestroj@nav.rwth-aachen.de>", "Erik Deinzer <erikdeinzer@gmail.com>"]
version = "0.1.3"

[deps]
BitIntegers = "c3b6d118-76ef-56ca-8cc7-ebb389d030a1"
CRC = "44b605c4-b955-5f2b-9b6d-d2bd01d3d205"
DocStringExtensions = "ffbed154-4ef7-542d-bbb7-c09d3a79fcae"
GNSSSignals = "52c80523-2a4e-5c38-8979-05588f836870"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"
ViterbiDecoder = "5f0870c7-49c9-4542-b5f1-5d9ed4caea51"

[compat]
BitIntegers = "0.2.6, 0.3.5"
CRC = "4"
DocStringExtensions = "0.6, 0.7, 0.8, 0.9"
GNSSSignals = "0.14, 0.15, 0.16, 0.17"
ViterbiDecoder = "0.1.0"
julia = "1.6"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
