name = "GNSSDecoder"
uuid = "bf6b1ec8-12ad-4501-972c-3dec0d675c2b"
authors = ["Soeren Schoenbrod <soeren.schoenbrod@nav.rwth-aachen.de>", "Michael Niestroj <michael.niestroj@nav.rwth-aachen.de>", "Erik Deinzer <erikdeinzer@gmail.com>"]
version = "0.0.1"

[deps]
BitIntegers = "c3b6d118-76ef-56ca-8cc7-ebb389d030a1"
DocStringExtensions = "ffbed154-4ef7-542d-bbb7-c09d3a79fcae"
GNSSSignals = "52c80523-2a4e-5c38-8979-05588f836870"
Parameters = "d96e819e-fc66-5662-9728-84c9c7592b0a"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[compat]
BitIntegers = "0.2.6"
DocStringExtensions = "0.6, 0.7, 0.8"
GNSSSignals = "0.14, 0.15, 0.16"
Parameters = "0.11, 0.12"
julia = "1.5"

[extras]
Suppressor = "fd094767-a336-5f1f-9728-57cf17d0bbfb"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test", "Suppressor"]
