# Reed-Solomon over GF(2^8) — the systematic block code and erasure decoder
# used by the Galileo High Accuracy Service (HAS) "High Parity Vertical
# Reed-Solomon" (HPVRS) outer layer on E6-B C/NAV (Galileo HAS SIS ICD,
# Issue 1.0, §6).
#
# The primitives here are signal-independent — field polynomial, code length and
# dimension are all parameters — and carry their own unit tests, like `crc.jl`
# and `deinterleave.jl`. `galileo/e6b.jl` instantiates them once for the ICD's
# RS(255, 32) code.
#
# The one thing worth stating up front, because it is what makes HPVRS useful:
# an RS(n, k) code over GF(2^8) with a *systematic* generator matrix G (n x k,
# leading k x k identity) can be decoded from **any** k received code symbols by
# pure linear algebra — no syndromes, no Berlekamp-Massey. Every received symbol
# is a known linear functional of the information vector, so k of them give a
# k x k system. Galileo exploits this by having each satellite broadcast a
# *different* row of the code (the page ID), so a receiver assembles one message
# from whichever pages it happens to hear (ICD §6.4). Symbols that fail the
# page CRC are simply not collected — a binary erasure channel — which is why an
# erasure decoder, rather than an error-correcting one, is the right tool.

"""
$(TYPEDEF)

Multiplication tables for GF(256), built from a primitive polynomial. Constructed
once and shared; all field arithmetic below takes it as its first argument.

The extension degree is fixed at 8, not a parameter: the tables are sized for 255
nonzero elements and the reduction step tests the carry out of bit 8, so only a
degree-8 primitive polynomial gives a valid field here. Only the polynomial
itself varies (Galileo HAS and CCSDS pick different ones).

# Fields

$(TYPEDFIELDS)
"""
struct GaloisField256
    """
    `exponentials[i+1] == α^i`, tabulated for `i = 0 … 2(order-1)` so that
    products can be looked up from a sum of logarithms without a modulo.
    """
    exponentials::Vector{UInt8}
    """
    `logarithms[x+1] == i` such that `α^i == x`, for `x = 1 … order-1`
    (`logarithms[1]` is unused — zero has no logarithm).
    """
    logarithms::Vector{UInt8}
end

"""
    GaloisField256(primitive_polynomial::UInt16)

Build the log/antilog tables for GF(256) generated by `primitive_polynomial`,
given in the usual wire form with the implicit `x^8` included (e.g. `0x11d` for
`p(α) = α^8 + α^4 + α^3 + α^2 + 1`).
"""
function GaloisField256(primitive_polynomial::UInt16)
    exponentials = zeros(UInt8, 512)
    logarithms = zeros(UInt8, 256)
    x = UInt16(1)
    for i = 0:254
        exponentials[i+1] = UInt8(x)
        logarithms[x+1] = UInt8(i)
        x <<= 1
        if x & 0x0100 != 0
            x ⊻= primitive_polynomial
        end
    end
    # α^255 == α^0, so the second half of the table repeats the first. This
    # lets `gf_multiply` add two logarithms (each ≤ 254) and index directly.
    for i = 255:511
        exponentials[i+1] = exponentials[i-255+1]
    end
    return GaloisField256(exponentials, logarithms)
end

"""
    GALILEO_HAS_GF256

GF(256) as the Galileo HAS SIS ICD defines it: primitive polynomial
`p(α) = α^8 + α^4 + α^3 + α^2 + 1` (ICD Issue 1.0, Eq. 7 — wire form `0x11d`,
the same field AES and CCSDS conventionally use).
"""
const GALILEO_HAS_GF256 = GaloisField256(UInt16(0x11d))

"""
Field addition — XOR, since the characteristic is 2.
"""
@inline gf_add(a::UInt8, b::UInt8) = a ⊻ b

"""
Field multiplication via the logarithm tables (`0` short-circuits).
"""
@inline function gf_multiply(field::GaloisField256, a::UInt8, b::UInt8)
    (a == 0x00 || b == 0x00) && return 0x00
    @inbounds field.exponentials[Int(field.logarithms[a+1])+Int(field.logarithms[b+1])+1]
end

"""
    gf_inverse(field, a) -> UInt8

Multiplicative inverse of a nonzero `a`: `α^-i == α^(255-i)`.
Throws on `a == 0`.
"""
@inline function gf_inverse(field::GaloisField256, a::UInt8)
    a == 0x00 && throw(DivideError())
    @inbounds field.exponentials[255-Int(field.logarithms[a+1])+1]
end

"""
    rs_generator_polynomial(field, num_parity) -> Vector{UInt8}

Generator polynomial of the narrow-sense Reed-Solomon code with `num_parity`
parity symbols, `g(x) = ∏_{i=1}^{num_parity} (x - α^i)`, returned
lowest-degree-coefficient first (`result[j+1] == g_j`). For the Galileo HAS
code (`num_parity = 223`) this reproduces HAS SIS ICD Table 42.
"""
function rs_generator_polynomial(field::GaloisField256, num_parity::Int)
    num_parity >= 1 || throw(ArgumentError("num_parity must be positive"))
    g = zeros(UInt8, num_parity + 1)
    g[1] = 0x01
    degree = 0
    for i = 1:num_parity
        root = field.exponentials[i+1]     # α^i
        # Multiply g(x) by (x - α^i) = (x + α^i) in characteristic 2.
        degree += 1
        @inbounds for j = degree:-1:1
            g[j+1] = gf_add(g[j], gf_multiply(field, g[j+1], root))
        end
        @inbounds g[1] = gf_multiply(field, g[1], root)
    end
    return g
end

"""
    rs_systematic_generator_matrix(field, n, k) -> Matrix{UInt8}

The `n × k` systematic generator matrix `G = [I; P]` of the narrow-sense
Reed-Solomon code RS(`n`, `k`), in the row/column order the Galileo HAS SIS ICD
fixes (Issue 1.0, Eq. 12-15 and Annex B): `Γ = G ⋅ c` where the information
vector is `c = [c_{k-1}, …, c_0]` and the code vector is
`Γ = [c_{k-1}, …, c_0, γ_{n-k-1}, …, γ_0]` — information part first, both parts
in descending coefficient order.

Column `i` is therefore the codeword of the `i`-th unit information vector:
rows `1:k` are the identity, and rows `k+1:n` hold the parity submatrix `P`,
with row `k + t` carrying `γ_{n-k-t}`. Reproduces the ICD's Annex B attachment
exactly for `(n, k) = (255, 32)`.

Erasure decoding (see [`rs_erasure_decode`](@ref)) needs only `G`, so this one
function is the whole codec a receiver requires.
"""
function rs_systematic_generator_matrix(field::GaloisField256, n::Int, k::Int)
    0 < k <= n <= 255 || throw(ArgumentError("need 0 < k ≤ n ≤ 255, got n=$n, k=$k"))
    num_parity = n - k
    g = rs_generator_polynomial(field, num_parity)
    G = zeros(UInt8, n, k)
    # `coefficients[d + 1]` holds the coefficient of x^d.
    coefficients = zeros(UInt8, n)
    for i = 1:k
        G[i, i] = 0x01
        # Information vector e_i sets c_{k-i} = 1, so `c(x) ⋅ x^(n-k)` is the
        # bare monomial x^(n-i) (ICD Eq. 9-11). Reduce it modulo the monic g(x)
        # by long division; what is left below degree n-k is the parity vector γ.
        fill!(coefficients, 0x00)
        coefficients[n-i+1] = 0x01
        @inbounds for degree = (n-i):-1:num_parity
            leading = coefficients[degree+1]
            leading == 0x00 && continue
            # g is monic of degree num_parity, so subtracting
            # leading ⋅ x^(degree - num_parity) ⋅ g(x) clears this term.
            shift = degree - num_parity
            for j = 0:num_parity
                coefficients[shift+j+1] =
                    gf_add(coefficients[shift+j+1], gf_multiply(field, g[j+1], leading))
            end
        end
        # ICD row k + t carries γ_{(n-k) - t} (Eq. 12: the parity part is listed
        # in descending coefficient order).
        @inbounds for t = 1:num_parity
            G[k+t, i] = coefficients[num_parity-t+1]
        end
    end
    return G
end

"""
    gf_invert(field, A) -> Union{Nothing,Matrix{UInt8}}

Matrix inverse over GF(256) by Gauss-Jordan elimination. Returns `nothing` if
`A` is singular. `A` is not modified.
"""
function gf_invert(field::GaloisField256, A::AbstractMatrix{UInt8})
    n = size(A, 1)
    size(A, 2) == n || throw(DimensionMismatch("matrix must be square"))
    M = Matrix{UInt8}(A)
    inverse = zeros(UInt8, n, n)
    @inbounds for i = 1:n
        inverse[i, i] = 0x01
    end
    @inbounds for col = 1:n
        pivot = 0
        for row = col:n
            if M[row, col] != 0x00
                pivot = row
                break
            end
        end
        pivot == 0 && return nothing
        if pivot != col
            for j = 1:n
                M[col, j], M[pivot, j] = M[pivot, j], M[col, j]
                inverse[col, j], inverse[pivot, j] = inverse[pivot, j], inverse[col, j]
            end
        end
        scale = gf_inverse(field, M[col, col])
        for j = 1:n
            M[col, j] = gf_multiply(field, M[col, j], scale)
            inverse[col, j] = gf_multiply(field, inverse[col, j], scale)
        end
        for row = 1:n
            row == col && continue
            factor = M[row, col]
            factor == 0x00 && continue
            for j = 1:n
                M[row, j] = gf_add(M[row, j], gf_multiply(field, M[col, j], factor))
                inverse[row, j] =
                    gf_add(inverse[row, j], gf_multiply(field, inverse[col, j], factor))
            end
        end
    end
    return inverse
end

"""
    rs_erasure_decode(field, G, received_rows, received::AbstractMatrix{UInt8}, k)
        -> Union{Nothing,Matrix{UInt8}}

Recover the information symbols of a systematic RS code from any `k` received
code symbols per column — the Galileo HAS HPVRS decode (HAS SIS ICD, Issue 1.0,
§6.4).

  - `G` is the systematic generator matrix from [`rs_systematic_generator_matrix`](@ref).
  - `received_rows` are the 1-based code-vector indices (HAS page IDs) of the
    `k` collected symbols, in the same order as the rows of `received`.
  - `received` is `k × J`: row `r` holds the `J` symbols of the code vector
    indexed `received_rows[r]` (for HAS, `J = 53` octets per page).
  - `k` is the information length actually in use. HAS transmits messages of
    `k = MS ≤ 32` pages and zero-pads the information vector to the code's
    dimension, so only the first `k` columns of `G` matter.

Returns a `k × J` matrix whose row `i` is information symbol block `i` (HAS
non-encoded page `M_i`), or `nothing` if the chosen rows are linearly dependent
(the `k × k` submatrix is singular).

!!! warning "Rows k+1 … (code dimension) carry nothing"

    The code is MDS, so *any* `k` distinct code symbols determine the message —
    with one exception created by the zero padding. When `k` is less than the
    code dimension, systematic rows `k+1 … dimension` are zero in the first `k`
    columns, because the information symbols they carry are the padding. Such a
    row contributes no equation and makes the submatrix singular. HAS therefore
    never transmits those pages ("Pages Ck+1, …, CK contain only zeroes and are
    excluded from transmission", ICD §6.3) and a caller must not collect them.
    Passing one, or the same row twice, is reported as `nothing` rather than
    silently producing garbage.
"""
function rs_erasure_decode(
    field::GaloisField256,
    G::AbstractMatrix{UInt8},
    received_rows::AbstractVector{Int},
    received::AbstractMatrix{UInt8},
    k::Int,
)
    length(received_rows) == k ||
        throw(DimensionMismatch("expected $k row indices, got $(length(received_rows))"))
    size(received, 1) == k ||
        throw(DimensionMismatch("expected $k received rows, got $(size(received, 1))"))
    k <= size(G, 2) || throw(ArgumentError("k=$k exceeds the code dimension $(size(G, 2))"))
    all(r -> 1 <= r <= size(G, 1), received_rows) ||
        throw(ArgumentError("row index out of range 1:$(size(G, 1))"))
    # D = G[received_rows, 1:k] — the ICD's decoding matrix (§6.4).
    D = Matrix{UInt8}(undef, k, k)
    @inbounds for r = 1:k, c = 1:k
        D[r, c] = G[received_rows[r], c]
    end
    Dinv = gf_invert(field, D)
    isnothing(Dinv) && return nothing
    # One inversion serves every column: m_j = D^-1 · w'_j.
    J = size(received, 2)
    out = zeros(UInt8, k, J)
    @inbounds for j = 1:J
        for i = 1:k
            accumulator = 0x00
            for r = 1:k
                accumulator =
                    gf_add(accumulator, gf_multiply(field, Dinv[i, r], received[r, j]))
            end
            out[i, j] = accumulator
        end
    end
    return out
end
